# Generated by Django 5.0 on 2024-05-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclistening',
            name='listen_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
