# Generated by Django 5.0 on 2024-05-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_delete_musiclistening'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='youtube_id',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
