# Generated by Django 5.0 on 2024-05-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_music_url_music_youtube_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
