# Generated by Django 5.0 on 2024-05-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_alter_music_url_alter_music_youtube_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='url',
        ),
    ]
