# Generated by Django 5.0 on 2024-05-26 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_remove_music_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='loading_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
