# Generated by Django 5.0 on 2024-05-26 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_music_loading_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-loading_time']},
        ),
    ]
